[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DARDUINO_ARCH_ESP32
    -O3
    -DCORE_DEBUG_LEVEL=0
    -I lib/glove_inference/src

lib_deps = 
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    Wire
    adafruit/Adafruit MPU6050 @ ^2.2.9

; --- THE EMERGENCY FILTER ---
; This tells PIO: "Ignore EVERY file in src, then ONLY look at the AI reader"
; We use a wildcard (*) to catch the filename even with the weird space.
src_filter = +<main.cpp> -<AI_Data_reader.cpp> -<main_data_read.cpp>

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
upload_speed = 921600