/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 13.04.2026 13:27:36

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1504;
#else
constexpr int kTensorArenaSize = 480;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,143 } };
const TfArray<1, float> quant0_scale = { 1, { 56.030769348144531, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -1, 8, -5, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.032299697399139404, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  72, 15, 111, -81, -47, 57, 89, -102, -116, 93, 
  70, 74, -59, -12, -118, 11, 34, -91, 21, -19, 
  -100, -22, 127, -27, -112, -98, -98, -63, 107, 30, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0051928665488958359, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 0, 3, 0, 3, -1, 0, 2, -2, -1, -1, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.065756142139434814, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  44, -82, -84, 18, 96, 0, 107, -125, -13, -55, 24, 9, 69, 118, 52, -104, -11, -33, -72, 27, 
  -61, -122, 77, 82, 42, -29, -53, -109, -56, 20, -69, -50, 83, -14, 76, 106, -52, 51, 61, -33, 
  -25, -105, -5, 115, -53, -70, -41, 0, -62, -12, 33, 53, -23, -94, -1, -77, 89, -108, -124, -88, 
  64, 15, 62, 3, -76, 82, -95, -59, -27, 80, 98, 39, -80, -102, -12, -48, -41, -77, 108, 92, 
  -49, 65, -107, -49, -94, 69, -42, 26, -112, 67, 98, 59, -23, 52, 24, -109, -57, 106, 58, 63, 
  -96, 76, -76, 55, -33, -127, -7, 85, -127, -51, 84, 65, -55, 68, -26, -74, -40, 67, -74, 4, 
  100, 50, -59, -77, 77, 92, 9, -37, -19, 3, 63, 47, -65, -79, 12, -14, 66, -3, 5, -38, 
  -16, 98, 48, 57, -4, 85, 98, -118, 115, -33, -63, 120, 53, -2, -108, 49, 93, -8, -11, 91, 
  68, 46, 61, 35, 104, 31, -112, -23, -32, 13, 106, 25, -27, -90, -34, 103, -92, 65, -46, -36, 
  48, -80, -24, -6, 91, 108, -30, 7, 57, -101, -63, 46, -81, -47, 58, -24, -22, 92, -86, 84, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035151408519595861, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.41568535566329956, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*143] = { 
  0, -4, -6, 21, 7, 12, 7, -16, 8, -20, -1, 9, -23, -17, -6, 22, 6, 18, -12, -12, 22, -7, 21, 4, -23, 16, -12, -13, -18, -23, 6, 8, 15, -21, -24, 11, -16, 18, -2, -16, 11, -2, -19, -8, -22, 21, -9, 22, -17, -18, -5, -24, 10, -6, -21, 16, 24, 19, 25, 15, 10, -10, 3, -18, -4, -18, 0, 8, 21, -3, 6, -22, -16, -7, -5, -14, 18, 12, -3, 21, 7, -1, -4, 8, -5, 3, -26, -3, -19, -24, 9, -6, -13, 21, -3, -24, 24, 13, -19, -10, -2, -26, 5, 13, -7, -10, -10, 1, -14, -12, 20, 7, 1, 16, -13, 23, -12, 9, -25, 8, 12, 0, 5, 23, -25, -5, 16, 1, 20, -4, -22, -15, 23, 7, 20, -14, 1, 25, -6, 1, 12, -1, -17, 
  -25, -2, 21, 3, -8, 4, 8, 7, 11, 23, -17, 10, 3, 4, 15, -14, 20, 13, 25, -16, -5, -3, 21, -5, 13, 12, -5, 19, -6, -19, -3, 23, 22, 24, 17, -8, -21, -3, 6, -12, -11, -14, 25, 19, 14, -7, 19, -18, 2, 0, -24, -3, 1, -9, -4, -26, -24, 20, 21, -21, -5, 17, -11, -5, -7, 0, 20, -25, 14, -7, 23, -15, 15, -2, 3, 20, -8, -15, -2, 22, -4, -25, -13, -1, 11, 2, -6, -19, 5, -6, 8, 8, 23, 6, 1, 15, -12, -21, 4, -23, 5, 24, -1, -4, -18, 12, 19, -17, -5, -5, -8, -23, 25, 7, -8, 22, 6, 5, -19, -18, 6, -24, -8, -14, 11, -3, -1, 9, -22, 24, -9, -8, 16, -8, 24, 16, -16, -9, -4, 15, -24, 3, -3, 
  17, -10, -24, -29, 7, -24, 8, 17, 27, -7, -26, -2, -26, 17, -2, -6, -14, -25, -8, 4, 28, -9, 18, -16, 7, -7, 24, 3, -78, -9, 11, 11, 2, -24, -4, -11, -22, -3, 9, -15, -44, 42, -31, -3, 4, -6, -6, -6, 11, -3, 13, -10, -9, -112, 24, -39, -5, -3, 1, -1, 36, -5, 0, 10, -2, 15, 75, 4, -6, 2, -6, -31, -2, 22, -6, -24, -23, 8, 1, -27, 13, 21, 48, 30, 20, 22, 11, 6, -17, 7, -13, 2, -17, 22, -20, -16, -16, -5, -6, -9, -26, -13, -26, -31, 8, 61, 37, -16, -23, -7, -7, 20, 3, -17, 6, 3, 38, 21, 7, -27, -18, -28, 27, -20, 29, 39, 20, 55, 13, 21, 0, -28, -7, -4, -3, -27, -46, -20, -31, -32, -31, 0, -7, 
  -25, 22, -10, 7, 3, 5, -12, 15, 3, -30, 11, 12, 3, 15, 12, -2, -30, -22, -1, 7, -25, 2, -25, -18, 7, 4, -18, 12, 23, 8, -11, 1, 12, -21, 6, -5, 16, -33, -4, 13, -27, 27, -11, 8, 14, -30, -11, -26, 5, 2, -26, -11, -11, -15, 13, -32, -34, -35, -20, -13, 14, -1, 15, 9, -27, -24, 8, -22, -25, -28, 5, -23, -23, -28, -3, -1, -15, 16, 14, 19, 6, 13, 25, -10, -6, -23, -5, -13, 13, -13, 7, -1, -18, -10, 14, -6, -26, -14, 12, -16, -18, -13, 8, -27, -19, -10, -13, -16, 7, -1, -30, -5, -9, 9, -8, 15, -32, -6, 22, -13, -33, 18, -6, 1, -30, -5, -8, -24, -1, 2, -19, -18, -12, 17, -2, -22, -25, -3, -9, 8, 6, 10, -1, 
  18, 31, -17, -13, 10, -31, 10, -16, -18, 6, -18, -6, -27, -6, -25, -1, 6, 12, -9, -13, -8, 18, -12, -11, -17, -6, 16, 32, -53, -18, 19, -26, 13, -28, -16, -23, -18, -35, -9, 6, 54, 17, -36, -34, 7, -24, 13, 9, -14, 8, 7, 9, -22, 23, -34, 8, -7, 14, 17, 11, -27, -28, 16, 17, -6, 9, -48, 0, -33, -11, -30, -1, 9, 1, 3, 3, -16, -15, -9, -23, 4, -11, 38, -13, 14, -10, 7, -13, 17, -3, -17, -5, 8, 11, 1, -5, -9, -20, -29, -37, -17, -33, -8, -18, 22, -48, -1, -14, -27, 2, -24, -10, -21, -11, 3, -6, -17, -16, -63, -32, 44, 11, -20, -10, -36, -1, 18, -24, -22, 0, -9, 16, -37, -7, -4, -29, -11, -15, -48, 2, -12, -23, -4, 
  -6, -24, -19, -5, -30, -9, 10, 30, -13, 11, -13, 1, -14, 4, -25, 8, -5, 48, -2, 5, -26, -36, -6, -16, 18, -4, 6, -31, 30, 4, -38, 0, 29, -10, 4, -21, 19, -11, 22, 19, 68, -42, -17, -4, 3, -30, -31, -32, -4, 12, 22, 0, 12, 88, -11, 34, 36, -3, 9, -9, -7, -29, 12, -27, -12, -4, -41, 43, 12, -7, 24, -11, 18, -21, -27, -15, -3, 2, -7, 39, -18, -33, -60, -25, -37, -52, -23, -26, 10, -29, -4, 32, 6, -7, 48, 41, 27, 31, 19, 33, -2, -1, 35, 1, 13, -62, -36, 5, 32, 14, -10, -17, -2, 7, -9, -27, -21, -14, -10, 46, -36, 59, -21, -3, 4, 0, -21, -47, -39, -43, 27, 17, 5, -2, 18, 82, 63, 45, 87, 81, 60, 50, 50, 
  9, -7, -5, -6, -18, -16, -2, 21, -13, 5, 5, 3, 6, 8, -10, 18, 10, 25, 32, 25, -16, -10, -16, 12, -14, -2, 21, -25, 73, -7, -15, -20, 9, 1, -22, 15, -24, 11, -16, 23, 40, -34, 5, 8, -9, -22, 17, -28, -5, -9, -17, 25, -20, 104, -15, 16, 21, 25, 14, -16, -29, -2, 14, -22, 7, 3, -80, -6, -24, -30, 7, 26, -6, 11, 8, 16, 13, 25, -5, -6, 23, -15, -32, -22, -33, -25, -1, -1, -15, -18, -23, 32, 10, -3, 26, 5, 8, -2, -11, 10, -16, -23, 13, 3, 27, -76, -18, 11, 6, 0, -7, 5, 12, -32, -17, -32, -12, -6, -44, 33, -17, 45, -26, -7, -17, -37, -17, -24, -39, -42, 23, -27, 8, 20, 24, 54, 5, 45, 60, 60, 34, 35, 19, 
  23, -110, -44, -2, 2, 5, 7, 12, -4, 27, 4, 35, 0, 8, -26, -23, -23, -16, -21, 18, 22, -5, -8, 7, 7, 32, -1, -42, -24, -20, 12, 16, -1, -22, -5, -15, 4, 15, 32, -2, -3, 28, 5, 19, -4, -13, 0, -13, -12, 14, -15, -7, -1, 8, 21, -24, 13, 4, 5, -31, -13, -5, 17, -15, 19, 12, 99, 98, -24, 21, -23, -3, -9, 12, -2, 6, -9, 13, -12, 19, 50, -32, 18, -9, -9, -39, 0, -11, 5, -29, -5, -6, -55, -15, -29, 14, -14, -21, -9, 13, -16, 8, -17, -35, 24, 29, -127, -77, 21, -8, -6, -23, 1, 21, 44, 1, 29, 7, 8, 39, -52, -8, -1, -18, 43, 12, -15, -1, 34, 18, 22, 21, 27, -28, -28, 34, 21, 32, 23, 10, 19, 80, 38, 
  16, -83, -70, -12, -26, 20, 2, -7, 12, 7, 17, 32, 30, -7, -79, -44, 20, 25, 34, 5, 32, 27, 35, 21, 32, 29, 15, -19, -31, -27, 35, -24, -4, 7, -12, 3, -9, 32, 5, -10, 64, -86, -43, -55, -25, 1, -11, 2, -10, 7, -18, -21, 10, 66, -33, 6, -11, 9, -10, -11, 22, -3, 26, -9, 5, -17, 20, 86, 16, -12, -9, -6, 9, -10, -5, -18, -14, -9, -12, 14, -15, 3, 10, -16, 16, -1, -3, -3, 5, 11, 9, -20, 9, -3, 47, 28, 26, 17, 18, -23, -33, -26, -19, 3, 25, -1, -55, -4, 27, 2, 1, 29, 13, 32, 30, 22, 0, -5, 7, 25, 16, 50, 9, 18, 52, -22, 0, 17, -14, 21, -6, 73, -46, -28, -51, 34, 19, 66, 32, 49, 49, 44, 65, 
  -21, 12, -22, -2, -15, 15, -23, 0, -14, -26, -22, -18, -26, -7, -16, 20, -3, 15, 18, -16, -5, 16, 5, 24, 26, 17, 1, 8, -1, 12, -11, -7, -19, -1, 18, 8, 17, 19, -4, 4, 6, 11, -14, 6, -11, -26, 17, 11, 22, -20, 13, 24, -25, -24, -15, 5, 14, 3, -23, 8, -23, -14, -18, 19, 0, -6, -24, -7, -18, 11, -16, 17, 22, 1, -5, -19, 24, -7, -26, 18, 13, 25, -22, -15, -18, 20, -18, -14, 12, 5, 20, 10, -7, -3, 3, 23, -1, -24, -20, -11, 16, -20, -22, -9, 4, -1, -26, -12, 10, 9, 12, -14, -11, -11, 22, 17, 20, 14, 17, 13, 20, -25, -12, 22, -14, 12, 18, -8, -13, 10, -12, -15, -9, -7, -22, 12, 22, -1, 4, -25, 20, -18, 9, 
  31, 2, -10, -29, -12, -19, 7, -4, -9, 1, -27, 0, -1, -12, 0, -22, -6, 3, 2, -2, -29, 5, -30, 13, 14, -12, -8, -7, 8, 10, -27, -29, -29, -14, 18, 14, -15, -28, -28, 1, 13, 0, -8, -15, -18, 9, -7, -32, 6, 1, -17, -25, -6, 1, 9, 12, -25, -19, -3, -12, -1, 0, 8, 9, -2, -20, -19, 1, 5, 8, 11, -5, -14, -18, -8, 15, -1, -24, 11, 13, -11, -23, 9, -24, -17, 9, -16, -1, -18, -19, -7, 20, 15, -16, -12, -3, -23, 2, -30, 4, 13, 8, 4, 1, 9, -5, 0, -29, 20, -5, -13, -6, 2, 6, -32, -3, -15, 18, -14, -27, -20, -30, -20, -25, 16, 6, -24, 0, 6, -29, 13, 1, -24, -30, 4, 3, -8, -30, 17, 9, -16, -25, -16, 
  -3, -90, -36, -39, -54, -33, 17, -15, 16, -7, 24, 26, 18, 17, -25, 1, -32, -20, 11, -13, -13, -2, 23, 1, 14, 10, 8, -41, 15, -14, -14, -20, -11, -17, 4, -6, -17, 8, 14, 5, -9, 30, -4, -20, -33, -25, -6, 13, -28, -9, -25, 8, 4, -22, 39, 2, 37, -23, -16, -33, 18, 10, -5, -12, 16, 13, 99, 103, -23, -20, -35, -14, -25, -22, 10, 1, 3, 11, 7, 32, 38, 5, -39, -32, -49, -45, -36, -18, -25, -14, 5, -9, -53, -15, -3, 41, 8, 18, -11, -17, -9, -8, 5, 7, 28, 43, -103, -28, 2, -24, -1, -2, 3, 13, -10, -12, -19, 2, 42, 48, -24, 2, 3, -4, 28, -7, -12, 1, 62, 38, -14, 38, 34, -38, -26, 26, 9, 58, 7, 26, 22, 65, 22, 
  -1, -36, -2, -29, -1, -43, -35, -44, -39, -7, -26, -44, -14, 11, -8, 48, -23, -38, 0, -28, -8, -5, -37, -4, -8, -30, 9, -19, 39, -29, -30, -15, -46, 2, -5, -5, -1, -39, -42, -15, -5, 23, -45, -40, -46, -30, 5, -5, -24, 5, -4, -44, -23, -18, -34, -30, 8, -11, -23, -9, -27, -38, -40, -2, -14, 4, 49, 8, -21, -5, -21, -33, -8, -5, -14, -47, -31, -1, -29, -20, -9, 7, 42, 2, 11, 5, -35, -32, -16, 2, -32, -3, 6, 20, -60, -62, -26, -36, -18, -39, -55, -16, -18, -27, -6, -15, 12, 3, 23, -3, -14, -16, -12, -24, -39, -16, -33, -32, -17, -28, -15, 11, -16, -33, -15, -8, -50, -9, -36, 0, -41, 23, -30, -23, 18, -15, -19, -49, -18, -13, -35, -39, -9, 
  3, -8, -19, -7, 18, 18, -28, 17, -11, 1, -1, 0, 17, 2, 17, -14, -33, -12, -27, -16, -26, -27, -8, -15, -18, -32, -20, 33, 6, -6, 2, -31, -25, -31, -10, 1, 5, -6, 16, -13, 30, 13, 13, -26, 15, -20, -8, 9, 20, 10, 2, 6, -24, -3, 32, -22, -11, 10, 6, -11, -6, -15, -11, -26, 10, 14, 28, 36, -4, 13, -28, -12, 9, -12, 5, -26, -21, -19, 5, -4, -14, 9, 2, -19, 1, -7, 7, 8, -12, -37, -7, 23, -29, 8, -14, 5, -11, 23, -4, -15, 6, 19, 3, -20, -21, -2, -26, -3, 0, 4, 8, -29, -22, -3, -22, 10, 7, -20, 8, -19, -20, -33, -20, -19, 19, -3, -23, 19, 5, 16, -20, -25, 8, -3, -18, -19, 15, -7, -12, 24, 28, -1, 3, 
  21, 20, 12, 23, 15, -5, -4, 13, 9, 11, 28, -22, -18, 22, -24, 1, 0, 36, 23, -13, 20, 9, -17, 14, -31, -16, -1, 8, 68, -9, 9, -6, 0, 22, -6, -17, -22, 5, 22, -25, 37, -22, -13, 14, 5, 20, -14, -31, -27, -14, -6, 15, 11, 102, -37, -5, 4, 3, 28, -17, -10, 7, -20, 17, -2, 21, -77, -45, -2, 8, 10, -8, 29, -10, 25, 14, -9, 13, -13, 16, -3, -17, -45, -31, -2, -27, 10, 6, -18, 8, -14, 27, 40, -10, 21, 24, 42, 36, 36, 43, -22, 16, -1, 32, -24, -90, 57, 21, 12, -14, -20, -8, 22, 6, -51, -11, -2, -18, 0, 48, 4, 48, -4, -20, -33, -35, -14, -15, -18, -42, 6, -14, -8, 26, 43, 49, 49, 40, 19, 57, 11, 16, 16, 
  0, 51, -5, -28, -12, -7, -13, -4, 8, 0, -14, -1, -27, 18, 39, 3, -17, -30, -1, 8, -22, 32, -21, 11, 4, -5, -10, 9, -46, -1, 33, -16, -21, 5, -4, -1, -5, -30, -6, 24, -36, 33, 1, -24, 13, -17, -17, 4, -20, 18, 7, -9, 12, -79, 23, -37, -5, 5, -20, 26, 10, -15, 5, -9, 5, 11, 35, -28, 5, 27, -28, 15, 15, 20, 7, 13, -15, -3, 43, -19, -19, 18, 41, 61, 52, 44, 25, 29, 23, 41, 3, 4, -7, 38, -15, -17, -47, -8, -4, -6, 17, 28, 10, -22, 11, 48, 48, -12, 7, -19, 9, -15, -23, 6, 34, 6, 15, -28, 14, -53, -8, -38, -5, -7, 7, 10, -3, 20, 17, -4, -20, -10, -18, 14, -25, -55, -53, -55, -49, -41, -47, -29, -49, 
  -1, 8, 5, 15, 29, 8, 2, -12, 9, -17, -14, -1, 15, 8, -27, 27, 8, 30, 23, 2, -22, -30, 7, -14, 7, -6, -3, 25, 28, 13, -15, 10, 34, -7, -7, -10, 9, -20, -5, 1, 62, -54, 20, 30, 7, -15, 16, -36, -1, -11, 5, 5, 1, 95, -24, 0, 10, 6, 23, -20, -27, 20, -16, -1, -21, 11, -73, -52, 2, 19, -12, 4, -6, 24, 24, 18, -7, 17, -35, 29, -11, -6, -63, -38, -18, 2, -16, -20, 22, -11, -4, 44, 50, -24, 49, 22, 29, 11, 41, 8, -1, -9, 13, 13, 23, -72, 22, 64, 17, -12, 9, -1, 15, -30, -49, -19, -34, 26, -48, 21, 25, 53, -17, -9, 13, -13, -17, -63, -15, -1, 13, 18, 11, 27, 0, 41, 48, 22, 74, 20, 50, 13, 46, 
  -3, -31, 24, -8, -13, -25, -27, 4, -8, -18, -24, 10, -25, 10, 29, 59, -45, -27, 2, -35, -4, -23, -35, 10, -28, -37, -19, -24, 5, -32, -10, -37, -17, -9, -13, 13, 12, -26, 8, -26, -87, 44, 7, -15, -11, -33, -11, 16, -31, 1, -24, -31, 13, -50, 28, -30, 37, -42, -24, -28, -2, -32, -1, 11, -17, 14, 92, 72, -9, -24, 3, -27, 1, 8, -4, -8, -35, -35, 23, -24, -2, -34, -23, -1, 1, 10, -23, -13, -7, -11, -11, 13, -47, -19, -21, -22, -10, -30, -3, -43, 8, 1, -19, -36, -16, 10, -111, -21, -17, -29, -25, -18, 13, -2, -9, 19, 31, 19, 16, -29, -65, -17, 0, 12, 4, 4, 9, 29, 36, 28, 6, 6, -1, 4, -15, -18, 18, 15, 0, -24, -36, -8, -33, 
  -20, 120, 78, 33, 69, 25, -2, 9, -2, -2, -16, -6, -19, -20, 19, 63, 65, 52, 8, 29, -3, 16, -7, 27, -14, -17, 9, 5, 42, -4, -20, 12, 8, -7, 35, 32, 17, -9, -10, -3, 6, 51, 23, 45, 28, 20, 43, 14, -1, -9, 17, -3, 12, 4, 27, 30, 23, 8, 16, 33, -2, -3, -5, 32, 26, -3, 21, -45, 27, 37, 42, 39, 40, -3, -5, 23, 42, 27, -16, 26, 1, 46, 50, 6, 21, 6, 17, 16, 22, -17, -40, 31, -9, 8, 26, -27, 41, 22, 39, 9, -12, 42, 23, 28, 5, -1, -9, -1, -36, 67, 12, 25, 9, 16, 10, 10, 51, 11, -46, -48, 15, -8, 21, 12, 6, 47, 6, -27, -9, 17, -13, -74, 9, 44, -8, 16, 9, 46, 43, 14, 41, 34, 25, 
  -1, 19, 1, -13, -4, -8, 8, -3, 18, 17, -21, 20, 18, 0, 0, -11, -1, -22, -14, 7, -10, -24, 20, -20, -2, 1, -17, -11, 9, 20, -18, 4, 22, -16, 2, 9, -23, 6, 2, -3, -17, -18, 7, 14, 0, -21, -24, 7, -2, 1, 7, 12, -22, 9, 12, -13, 14, -21, -17, 21, -20, 17, -19, 9, -19, -3, -4, -17, -19, -15, -25, 17, -8, -4, -6, 9, -21, -25, -22, -11, 20, -2, -1, -22, -5, 9, 23, -3, 7, 0, -24, 4, -17, -6, 8, -21, -17, -18, 26, -15, -8, 20, 17, -20, -5, 16, -24, -18, -2, 15, 26, 19, -22, -16, 11, 3, -2, -14, -12, -2, 25, 4, 11, -13, 7, 17, -23, 0, -13, 0, -18, 0, 21, 14, 3, 25, 12, 20, -14, -10, 10, -17, 9, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,143 } };
const TfArray<1, float> quant6_scale = { 1, { 0.007418876513838768, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 18.706544876098633, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 6.2200131416320801, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 4.5265779495239258, } };
const TfArray<1, int> quant9_zero = { 1, { -30 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 143, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2860, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 144), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_959943_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_959943_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_959943_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_959943_4_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_959943_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
