/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 11.04.2026 09:36:06

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1504;
#else
constexpr int kTensorArenaSize = 480;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,143 } };
const TfArray<1, float> quant0_scale = { 1, { 37.456356048583984, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { 1, 2, -3, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.040456276386976242, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  74, 22, 119, -111, -50, 61, 88, -106, -127, 89, 
  72, 74, -24, -68, -114, 18, 40, -95, 15, -19, 
  -98, -30, 119, 0, -111, -103, -108, -66, 113, 26, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0051953219808638096, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -2, 0, -1, 0, 0, 1, 2, -3, -1, -1, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.038665600121021271, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  42, -80, -82, 21, 97, 21, 111, -127, -1, -52, 22, 19, 12, 113, 49, -81, -9, -26, -73, 25, 
  -60, -118, 69, 78, 57, -34, -50, -118, -74, 19, -58, -49, 84, 23, 77, 100, -57, 40, -43, -32, 
  -23, -100, -11, 106, -56, -73, -45, 9, -42, -13, 29, 44, -27, -89, -20, -77, 78, -107, -103, -83, 
  61, 14, 103, 1, -43, 74, -50, -40, -29, 75, 96, 46, -54, -96, -7, -55, -40, -74, 109, 87, 
  -47, 62, -95, -44, -84, 61, -29, 30, -105, 63, 56, 49, -21, 51, 16, -109, -55, 91, 74, 59, 
  -90, 72, -65, 55, -34, -109, 0, 88, -121, -48, 85, 69, -21, 52, -18, -57, -31, 70, -70, 4, 
  94, 49, -58, -75, 76, 89, 6, -49, -13, 4, 63, 50, -57, -53, 19, -10, 60, -5, -14, -36, 
  -18, 94, 45, 54, -10, 79, 88, -99, 106, -32, -60, 108, 44, -15, -112, 43, 88, -4, 11, 87, 
  62, 42, 57, 42, 96, 35, -105, -18, -30, 12, 99, 23, -20, -101, -39, 98, -89, 56, -52, -34, 
  43, -74, -20, -8, 77, 98, -28, 13, 55, -95, -62, 45, -88, -60, 53, -26, -18, 97, 0, 80, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0037136794999241829, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.26529616117477417, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*143] = { 
  -2, -4, -6, 21, 7, 12, 7, -18, 8, -22, -2, 9, -25, -19, -6, 24, 6, 19, -14, -14, 22, -8, 21, 4, -25, 16, -15, -13, -18, -25, 6, 7, 15, -23, -26, 10, -18, 18, -4, -19, 12, -2, -21, -9, -24, 21, -10, 22, -18, -20, -6, -26, 9, -6, -22, 16, 24, 19, 25, 15, 9, -12, 2, -20, -5, -20, 0, 9, 22, -4, 5, -24, -17, -8, -7, -16, 17, 11, -4, 22, 8, -2, -5, 8, -6, 3, -27, -3, -20, -25, 9, -7, -13, 21, -3, -25, 25, 14, -21, -11, -2, -27, 5, 13, -8, -11, -11, 1, -15, -13, 21, 7, 1, 17, -14, 24, -12, 9, -27, 8, 12, 0, 5, 24, -27, -5, 16, 1, 21, -4, -24, -16, 25, 7, 22, -15, 1, 25, -7, 1, 13, -1, -18, 
  -26, -2, 22, 3, -8, 4, 8, 8, 12, 25, -17, 11, 4, 5, 16, -14, 21, 13, 27, -16, -4, -3, 22, -5, 14, 13, -5, 19, -6, -20, -4, 25, 23, 26, 18, -8, -21, -2, 7, -12, -11, -15, 26, 19, 15, -7, 20, -19, 2, 0, -24, -3, 1, -10, -4, -27, -25, 21, 22, -21, -5, 18, -11, -5, -7, 0, 20, -27, 15, -7, 24, -15, 16, -2, 4, 22, -8, -15, -2, 24, -4, -27, -14, 0, 12, 2, -5, -19, 5, -6, 8, 8, 24, 6, 1, 15, -13, -22, 4, -24, 6, 25, 0, -4, -19, 12, 20, -17, -5, -5, -8, -23, 26, 8, -8, 23, 7, 5, -20, -19, 7, -25, -8, -14, 12, -2, -1, 10, -22, 25, -9, -8, 17, -8, 25, 16, -17, -8, -4, 17, -25, 4, -3, 
  19, -4, -52, -14, 23, -15, 15, 21, 24, -1, -25, -2, -21, 18, -15, 23, 8, 8, 5, 12, 23, -29, 12, -28, -6, -15, 27, 26, -9, -20, -3, 17, 12, -21, -5, -10, -31, -9, 8, -15, 23, 25, -26, -2, 10, -7, -17, -24, 7, -10, 7, -13, -8, -36, -2, -21, 14, 0, -1, -12, 23, -6, -6, 1, -10, 18, 23, -13, -10, -7, -3, -27, -1, 20, -8, -29, -28, 8, 3, -50, 6, -2, 34, 16, 20, 14, 11, 15, -20, 5, 13, 11, -1, 8, -11, -24, -22, -16, -28, -21, -45, -42, -36, -35, 4, -66, 5, -23, -42, -20, -20, 12, 2, -19, -16, -28, 22, 17, -17, -18, -29, 20, 15, -32, 16, 13, 4, 14, -34, -12, 10, 73, -56, -29, -4, 11, -7, 40, 24, 25, -1, 29, 39, 
  -22, 15, -13, 12, -8, 13, -5, 24, 11, -25, 19, 19, 10, 18, 13, -5, -23, -16, 7, 15, -20, 8, -20, -12, 14, 11, -21, 19, 26, 14, -16, 9, 20, -14, 13, 1, 24, -28, 2, 18, -25, 20, -3, 18, 23, -23, -3, -19, 14, 10, -20, -3, -7, -31, 9, -21, -22, -28, -13, -5, 22, 7, 23, 17, -20, -23, 13, -20, -20, -27, 13, -16, -17, -22, 4, 7, -9, 25, 9, 27, 7, 17, 23, -9, -5, -23, -2, -13, 17, -11, 9, 8, -23, 5, 15, -21, -20, -8, 17, -9, -11, -6, 18, -19, -13, 0, 7, -12, -4, 6, -24, 3, -1, 19, 0, 23, -24, 1, 15, -6, -30, 17, 0, 6, -25, -1, -2, -19, 5, 7, -11, -23, -10, 22, -3, -15, -20, 5, 0, 17, 15, 15, 6, 
  17, -32, 10, -27, -32, -30, 14, -15, -24, 5, -16, -4, -25, -12, -29, 57, -5, -13, -13, -15, -12, 15, -16, -16, -20, -8, 16, 13, -1, -35, -10, -27, 16, -27, -18, -22, -17, -32, -2, 17, 46, 53, -37, -26, 3, -27, 10, 5, -16, 7, 6, 8, -20, -6, 21, 16, -1, 12, 15, 4, -35, -32, 15, 15, -7, 13, -24, 76, -41, -28, -35, -3, 9, -2, 1, 2, -19, -19, -23, -25, 35, -39, -3, -30, 2, -27, 0, -26, 11, -16, -18, 2, 45, -4, -4, -14, -2, -12, -25, -18, -8, -26, 7, -12, 25, 7, 5, -14, -21, 5, -18, -3, -24, -6, 9, -3, -8, -12, -21, 12, 12, -17, -16, -3, -22, 1, 26, -16, -9, 10, -8, -29, -15, 4, 10, -9, 9, 16, -26, 17, 4, -5, 13, 
  -9, 59, 48, 3, 7, -21, 1, 27, -9, 5, -22, -5, -26, 8, 15, -21, -12, 44, -10, 0, -17, -18, 2, -5, 30, 1, 5, -6, -4, 33, 10, -3, 18, -17, 5, -23, 23, -11, 16, 20, -10, -28, -9, 14, 8, -25, -16, -13, 5, 23, 32, 4, 6, 6, 22, 16, 14, -2, 16, 7, 10, -26, 19, -18, -5, -2, -18, -7, 36, 39, 30, -9, 23, -14, -21, -8, 4, 4, 8, 50, -42, 12, -10, 16, -19, -21, -8, -16, 23, -8, -35, 13, -54, 12, 38, 48, 24, 36, 30, 34, 8, 18, 31, -8, 15, 22, 6, 28, 67, 30, 3, -1, 11, 9, 13, 3, 1, -10, 8, -3, 4, 51, -9, 9, 9, 30, -4, -13, -5, -18, 6, -72, 49, 30, 26, 19, 2, -52, 2, 2, 4, -8, -19, 
  11, 2, 16, -22, -24, -30, -13, 16, -13, -4, -1, -2, -3, 9, 4, -18, -12, -4, 18, 15, -15, 3, -15, 18, -8, -1, 25, -24, 11, 2, 8, -30, -4, -7, -26, 12, -22, 12, -20, 24, -14, -14, -4, 1, -18, -26, 24, -17, -5, -8, -16, 24, -19, 49, 21, -7, -3, 21, 13, -10, -20, -5, 16, -18, 10, 4, -37, 8, -21, -13, 1, 20, -9, 11, 6, 17, 13, 22, 0, 19, 20, 2, -19, -9, -33, -18, -3, -9, -17, -21, -50, 25, -16, 11, 23, 10, 13, 8, 8, 19, -1, -2, 19, 4, 32, 36, 4, 19, 23, 7, -1, 10, 12, -35, -1, -8, -1, -4, -16, 14, -4, 6, -16, 2, -7, -17, -4, 9, -2, -18, 15, -101, 51, 49, 29, 18, -32, -13, 5, 6, 1, 6, -30, 
  25, 48, 23, 40, 50, 20, 16, 21, 5, 36, 4, 35, 1, 12, 14, -92, 20, 34, -2, 35, 34, -5, 0, 14, 9, 38, -3, 28, -17, 17, 47, 36, 12, -15, 2, -13, 4, 15, 27, -5, -66, -59, 50, 66, 27, 10, 19, -7, 1, 31, -3, 9, -3, -27, -24, -9, -5, 29, 27, -12, -2, 8, 27, -7, 26, 14, 34, -85, 10, 64, 2, 19, 9, 28, 15, 21, 6, 31, 3, 43, -9, -1, 54, 20, 15, -8, 23, 24, 21, -2, 0, -18, -57, 5, -4, 25, -1, -14, -2, 14, -9, 15, -10, -19, 4, -71, -78, -1, 57, 6, -6, -7, 25, 26, 26, -12, 27, 1, -27, -9, 20, 64, 16, -3, 28, 23, -5, -18, 0, 4, 21, 59, 5, 8, -6, 22, 4, -9, 0, 1, 1, 29, 22, 
  5, 68, 36, -7, -16, 10, -11, -22, -8, -10, -4, 10, 10, -17, 22, -27, 9, -7, 20, -2, 18, 13, 19, 7, 13, 12, 6, 16, 35, -31, 7, -33, -13, -8, -29, -14, -31, 16, -24, -6, -34, -24, -29, -14, -29, 2, -15, -9, -19, 3, -30, -32, 14, -22, 40, 5, -5, 7, -9, -15, 11, -12, 16, -18, -6, -33, 42, 8, 10, -19, -16, -13, 0, -25, -13, -28, -24, -17, -7, 26, -18, -15, -12, -6, 25, 8, 0, 15, 15, 17, -2, -20, -51, -28, 35, 30, 24, 6, 7, -24, -25, -25, -19, 11, 6, 11, -14, 13, 24, -2, -14, 16, 0, 10, 15, 18, 3, -11, 31, -13, 13, 44, 6, -4, 15, -25, 6, 19, -24, 16, -24, 41, -29, -1, -6, -6, -26, 13, -4, 14, 14, -7, 9, 
  -23, 12, -23, -2, -16, 15, -25, -1, -15, -28, -24, -19, -28, -8, -18, 20, -3, 16, 18, -18, -6, 16, 5, 24, 26, 18, 1, 8, -1, 12, -12, -8, -20, -1, 18, 8, 18, 20, -4, 3, 5, 11, -15, 7, -12, -27, 17, 10, 23, -21, 13, 25, -26, -25, -16, 4, 15, 2, -25, 8, -25, -15, -19, 20, 0, -7, -26, -8, -19, 12, -17, 17, 23, 0, -5, -21, 24, -8, -27, 18, 14, 25, -23, -16, -20, 20, -19, -15, 12, 4, 21, 10, -8, -3, 2, 24, -1, -26, -21, -13, 16, -21, -24, -10, 3, -1, -26, -13, 10, 9, 12, -15, -12, -12, 22, 17, 21, 14, 18, 14, 21, -27, -14, 22, -15, 12, 19, -9, -14, 10, -13, -15, -9, -8, -23, 12, 23, -1, 4, -27, 20, -19, 9, 
  25, 5, 11, -27, -22, -12, 14, 3, -3, 8, -22, 7, 6, -23, 12, -17, -1, 0, 8, 4, -24, 11, -26, 20, 21, -6, -13, -11, 19, 17, -26, -23, -23, -7, 25, 22, -9, -22, -22, 4, 10, -4, 1, -8, -10, 17, 0, -27, 14, 9, -10, -18, -3, -2, 18, 24, -12, -13, 5, -5, 6, 8, 16, 17, 6, -31, -26, 11, 11, 8, 19, 1, -8, -12, -2, 22, 6, -18, 12, 25, -11, -19, 8, -19, -12, 17, -10, 7, -11, -15, -1, 23, 9, -9, -7, -2, -17, 7, -26, 11, 21, 14, 11, 9, 11, -14, 6, -27, 17, 0, -8, -1, 7, 11, -28, 2, -10, 21, -9, -15, -15, -24, -18, -22, 20, 11, -21, 4, 11, -26, 15, -7, -22, -28, 5, 6, -5, -26, 23, 14, -13, -21, -14, 
  -5, 84, 67, 2, 19, -26, 19, -15, 18, -8, 19, 21, 13, 18, 12, -39, 11, 51, 24, -5, -7, -6, 28, 5, 14, 12, 11, 38, 42, 21, 41, -11, -10, -18, 2, -8, -23, 1, 3, 10, -37, -42, 39, 38, -10, -11, 7, 16, -18, 3, -16, 22, 3, -17, 17, 10, 28, -9, -3, -21, 22, 15, -2, -9, 17, 14, 34, -65, 12, 41, -14, 3, -12, -10, 26, 14, 17, 27, 29, 51, -29, 42, 19, -2, -34, -14, -24, 5, -15, 12, -10, -15, -98, -8, 26, 53, 23, 31, 0, -13, -7, -8, 8, 13, 22, -29, -49, 62, 54, -13, -5, 8, 19, 4, -38, -32, -35, 6, -10, -4, 61, 88, 10, 1, 5, -7, -15, -29, 24, 16, -17, 38, 48, 18, -8, -4, -30, -11, -37, -6, -19, -2, -20, 
  -7, -46, -127, -2, -22, 4, 16, 2, 1, 38, 17, -5, 31, 14, -41, -6, 3, -64, 50, 20, 33, 32, -3, 30, 23, 8, 7, -3, -25, -5, -60, 36, 8, 54, 44, 41, 45, 3, -3, -5, 16, 41, -14, -39, -5, 17, 47, 34, 13, 46, 34, -7, -18, -7, 9, -20, -63, 41, 28, 35, 13, 8, 6, 42, 30, 7, 26, 29, -4, -34, 15, 7, 31, 31, 21, -16, 3, 33, 3, -70, 41, 23, 6, 44, 66, 24, 13, 29, 26, 36, 48, 6, 101, 29, -38, -89, 0, -8, 5, 9, 5, 34, 42, 36, -1, 10, 54, -20, -81, 14, 19, 23, 25, 33, 22, 34, 31, -25, -14, 86, -9, -50, 20, 8, 30, 36, 10, 34, -5, 50, 30, 68, -65, -13, 9, 68, 69, 77, 83, 82, 61, 47, 76, 
  7, -20, 8, -7, 15, 23, -26, 22, -7, 3, 2, 4, 21, 5, 21, 0, -30, -7, -25, -13, -24, -25, -5, -12, -15, -30, -20, 33, 13, 0, 9, -29, -23, -30, -7, 3, 9, -5, 19, -11, 11, 18, 19, -21, 19, -17, -5, 12, 23, 13, 5, 9, -26, -17, 28, -14, 1, 15, 10, -9, -3, -13, -8, -24, 14, 14, 33, 31, 1, 22, -26, -9, 13, -9, 9, -24, -19, -16, 8, -13, -12, 9, -12, -14, 11, 0, 13, 18, -6, -33, -4, 4, -13, 4, -24, -12, -14, 21, -4, -17, 1, 19, 4, -22, -21, 4, 0, -8, -13, 6, 13, -28, -21, 2, -22, 9, 10, -19, 19, -27, -4, -3, -18, -11, 21, 0, -27, 17, 6, 20, -25, -31, 14, -1, -15, -29, 10, -13, -15, 20, 18, -8, 10, 
  22, -57, 4, -7, -20, -20, -14, 7, 8, 2, 27, -25, -26, 23, -40, 12, -36, -12, 5, -26, 21, 25, -17, 19, -23, -14, -2, -48, 8, -16, 3, -18, -13, 15, -9, -21, -17, 10, 25, -24, -12, 48, -35, -4, -11, 14, -12, -21, -30, -16, -5, 12, 15, 41, -1, -20, 13, -7, 24, -16, -3, 2, -19, 23, 2, 23, -7, 49, -14, -7, -4, -22, 21, -15, 20, 12, -13, 6, -20, 17, 38, -19, -56, -37, -12, -38, 1, -15, -23, -2, -40, 21, 24, -7, 16, 40, 57, 54, 69, 64, -1, 47, 12, 37, -15, 59, 56, 12, 32, -5, -7, -4, 18, 6, -25, 22, 14, -13, 48, 56, -12, -28, 5, -15, -16, -13, -3, 29, 38, -6, -5, -111, 65, 41, 34, 14, 16, -5, -30, 5, -14, -1, -26, 
  1, -7, -54, -25, -27, 6, -4, 3, 7, 9, -7, 5, -17, 18, 12, 44, -6, -16, 11, 17, -29, 18, -27, 3, -5, -9, -11, -10, 1, -19, 2, -10, -9, 13, -2, 3, -7, -31, 0, 25, 41, 23, -1, -35, 16, -20, -29, -12, -25, 13, 2, -11, 15, -3, 0, -17, 21, 8, -23, 16, -3, -16, 2, -16, 1, 11, 14, 8, -7, -1, -28, 18, 16, 17, 5, 10, -19, -3, 31, -31, -7, -11, 15, 34, 43, 24, 20, 27, 17, 31, 33, 16, 27, 25, -12, -26, -52, -16, -20, -10, 4, 8, 9, -21, 11, -49, 12, -33, -20, -30, 3, -24, -28, 9, 21, -17, 4, -32, -5, -24, -37, -12, -14, -15, 3, -14, -17, -11, -16, -28, -9, 72, -57, -17, -31, -9, -7, 19, 17, 24, -7, 13, 6, 
  1, -24, 20, -2, 11, -1, -3, -13, 16, -21, -14, 3, 12, 10, -11, 7, -16, -3, 11, -5, -14, -7, 17, 0, 25, 3, -1, 1, -30, 23, 2, 5, 27, -9, -4, -8, 21, -11, 0, -1, -14, -13, 9, 16, 1, -15, 28, -18, 5, -4, 13, 8, 0, 22, 13, -20, -10, 2, 26, -9, -12, 24, -10, 10, -12, 11, -18, -11, 5, 24, -17, -1, -7, 30, 27, 24, -4, 18, -40, 39, 13, 14, -55, -25, -17, 11, -13, -28, 31, -6, -27, 37, 34, -16, 46, 34, 36, 23, 66, 19, 17, 17, 21, 14, 32, 83, 37, 68, 42, 0, 23, 9, 19, -27, -22, 18, -17, 33, 4, 10, 30, -8, -5, 2, 32, 14, -1, -21, 36, 36, 0, -85, 68, 48, -2, 4, 14, -38, 19, -38, 23, -9, 3, 
  -5, 66, 20, 27, 32, -3, -8, 26, 15, 4, -8, 25, -6, 19, -6, -44, -4, 28, 35, -10, 18, -9, -14, 30, -12, -19, -18, 33, 10, -10, 12, -17, 1, 9, 7, 30, 24, -17, 18, -23, -46, -62, 40, 20, 16, -14, 7, 30, -15, 20, -9, -13, 20, -30, -7, -26, 12, -22, -6, -10, 13, -13, 17, 27, -3, 13, 20, -53, 21, 18, 28, -4, 23, 30, 18, 11, -17, -16, 35, -10, -48, 1, 15, 30, 29, 42, 4, 19, 2, 16, 17, 20, -49, 2, 1, -4, -2, -23, -4, -42, 14, 2, -15, -24, -19, -77, -51, 21, 0, -25, -23, -3, 32, 12, -19, 3, 30, 25, -53, -16, -7, 61, 12, 34, 9, 16, 21, 25, 22, 19, 13, 76, -69, 15, 3, -2, 33, 25, 10, 5, -24, -14, -9, 
  -25, -7, 16, -28, 11, 0, -20, -5, -3, -11, -27, -12, -25, -21, -19, -12, 0, -18, -17, 8, -15, 20, -17, 19, -14, -26, -3, -6, -22, -21, 10, -14, -19, -26, 25, 19, 5, -20, -23, -11, -21, 7, -18, 12, -1, -6, 25, 4, -23, -27, -1, -25, 10, -17, 19, -21, -20, -19, -9, 17, -11, -16, -20, 19, 11, -16, 22, -20, -1, 22, 15, 13, 18, -14, -27, 6, 22, 3, -10, 9, 10, 9, 24, -3, 11, 3, 21, 1, -4, -23, -28, 19, 16, -10, -21, -18, 13, 4, 23, -18, -29, 25, 4, 1, -15, -1, -16, -21, 1, 13, -20, 1, -29, -16, -17, -22, 10, 9, -22, -22, 22, -15, -9, 3, 6, 24, -8, -13, 0, 0, -26, -10, 3, -4, -4, -17, 5, 24, -13, 6, 17, -10, -6, 
  -1, 20, 1, -13, -5, -9, 8, -4, 19, 18, -22, 21, 19, 0, 0, -11, -1, -23, -14, 7, -10, -25, 21, -21, -2, 1, -17, -11, 9, 21, -19, 4, 23, -17, 2, 9, -25, 6, 2, -3, -18, -19, 7, 15, 0, -22, -25, 7, -3, 1, 7, 12, -23, 9, 12, -14, 14, -22, -18, 22, -21, 18, -20, 9, -20, -3, -4, -18, -19, -16, -26, 18, -8, -4, -6, 9, -22, -26, -24, -12, 21, -2, -1, -23, -5, 10, 24, -3, 8, 0, -25, 4, -18, -6, 8, -22, -18, -19, 27, -16, -8, 20, 18, -21, -5, 17, -25, -19, -2, 16, 27, 20, -23, -17, 12, 3, -2, -15, -12, -2, 27, 4, 12, -13, 8, 18, -24, 0, -14, 0, -19, 0, 22, 15, 3, 26, 13, 21, -14, -11, 10, -17, 9, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,143 } };
const TfArray<1, float> quant6_scale = { 1, { 0.007082807831466198, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 10.41166877746582, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 7.7870588302612305, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 4.5132865905761719, } };
const TfArray<1, int> quant9_zero = { 1, { 62 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 143, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2860, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 144), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_958037_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
