/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 13.04.2026 10:25:18

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1504;
#else
constexpr int kTensorArenaSize = 480;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,143 } };
const TfArray<1, float> quant0_scale = { 1, { 0.77065324783325195, } };
const TfArray<1, int> quant0_zero = { 1, { -115 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[6] = { 147, 139, -79, 72, -175, -110, };
const TfArray<1, int> tensor_dimension1 = { 1, { 6 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0024361934047192335, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[6*10] = { 
  -3, 54, -17, 79, -127, 42, 10, 19, -86, -25, 
  58, 23, -59, 11, 55, -32, 28, -19, 70, -65, 
  -34, 57, -81, -86, 49, 75, -53, -33, -26, 15, 
  41, -39, 41, -41, 47, -54, -105, 55, -90, 26, 
  -5, -105, 18, -59, -26, 17, 10, 20, 75, 8, 
  -30, -8, -117, -9, -23, -54, 85, 5, 1, 81, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 6,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.011764896102249622, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -11, 36, 42, 63, -83, 88, 0, 48, 18, 34, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0020309519022703171, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  32, -41, -74, -7, 42, -13, 63, -66, -3, -56, 14, -2, 36, 46, 16, -25, 0, -66, -7, 0, 
  -7, -86, 20, -2, 39, -20, -38, -34, -44, 46, -11, -31, 44, 3, 49, 59, -11, 5, -2, -31, 
  -40, -20, 8, 127, 2, -40, -28, 18, -42, 7, -4, 24, 17, -19, -16, -14, 2, -49, -11, -72, 
  45, 1, 47, -3, -43, 16, -39, -20, -20, 38, 88, 31, -44, -28, -11, -9, -44, -42, 79, 52, 
  -42, 42, -58, -40, -29, 64, -11, 8, -53, 39, 71, 23, -8, 35, 49, -68, -57, 71, 18, 87, 
  -31, 44, -53, -11, -12, -51, -13, 57, -45, -55, 53, 56, -47, 39, -2, -3, -14, 26, -23, -9, 
  66, 25, -28, -29, 60, 60, 9, -5, -23, 41, 45, 31, -59, -26, -14, -24, 78, -63, -8, -42, 
  -60, 40, 49, 79, -19, 25, 63, -60, 61, 2, -103, 37, 35, -12, -45, 38, 92, 21, 38, 35, 
  66, 24, 30, 82, 51, 24, -75, -21, 3, -26, 88, 3, 2, -86, -46, 54, -57, 27, -46, 16, 
  21, -29, 29, 15, 38, 76, -13, 6, 6, -38, -21, 29, -85, -44, 62, -16, -60, 74, 23, 35, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0082098543643951416, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 9, -3, 11, 9, -1, -8, -3, -2, -3, 0, 16, 0, 7, 3, -3, 13, -1, -6, 8, -6, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.009754035621881485, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*143] = { 
  1, 8, -20, 9, -15, 7, -4, -16, 2, -14, -2, 1, -17, -4, 13, 1, 9, 16, -7, -10, 5, -5, 9, 1, -16, 5, -12, -18, -15, -22, -22, -3, 8, -18, -12, 4, -15, 6, -7, -9, 10, -3, -8, -9, -2, 27, -4, 30, 2, -15, -3, 13, -1, 48, 27, -2, -25, 21, 24, 11, 25, 11, 4, -14, -22, -12, -9, 18, 18, -6, 21, -1, -20, 17, 7, 17, 22, 20, 17, 17, -4, 3, -20, 23, 6, 18, -8, 10, -1, -6, 7, 83, -50, 7, 8, 3, 40, 21, 2, 2, 6, -10, 11, 11, -4, -8, -4, 7, -6, -5, 14, 6, 3, 12, -6, 15, -6, 5, -18, 2, 12, -6, 3, 15, -14, -1, 10, 0, 12, -1, -47, -19, 8, 3, 23, -16, -7, 6, -11, -7, 0, -8, -17, 
  -2, -7, -30, 5, -1, 1, 4, 2, 6, 17, -11, 4, -1, -13, -4, -8, 7, -5, 21, -5, -8, -6, 11, -5, 4, 4, -8, 20, 15, -17, -9, 12, 6, 9, 14, -8, -16, -6, 6, -21, -2, -1, 9, 1, -1, -21, -6, -16, -8, 1, -29, -6, 5, 23, -23, -15, -19, 10, 5, -18, -7, 20, 0, 16, 1, 1, -5, -17, -1, -16, 2, -14, 4, -3, -5, 5, -6, -23, 9, -41, -20, 7, 5, -1, 3, -2, -10, -12, -5, -9, -9, -36, 17, -7, -44, -19, -30, -30, -11, -28, -12, 3, -14, -18, -32, 8, 3, 1, -27, -9, -10, -19, 10, 0, -8, 9, -1, 10, -8, -2, 17, -30, -10, -13, 2, -9, -5, 1, -17, 12, -9, -5, 1, -16, 3, 7, -9, -5, -4, 9, -16, 0, -5, 
  29, 1, 13, -10, 9, -14, 3, 12, 13, -2, -6, 6, -10, -11, -14, -2, 9, 21, -24, -8, 9, -18, 0, -14, -3, -5, 34, -38, -11, -4, 2, 4, 10, -6, -2, -2, -10, 1, 6, -20, -10, -7, -4, 12, 8, 0, 7, -2, 17, -2, 21, 23, 0, -21, -2, -13, 8, 4, 1, 4, 33, -9, 2, -7, -5, 9, 0, 0, 14, 20, 10, -21, -3, 14, 12, 7, 8, 33, -2, -5, -1, -9, -13, -6, -7, -4, -11, -9, -19, -7, -17, 13, 13, -2, 32, -2, 10, 9, 6, 5, -13, -15, -6, -11, -38, -5, 13, 4, 14, -4, -9, 6, -3, -15, -13, -16, 4, 5, 1, 8, 8, 8, 21, -9, 19, 20, 9, 15, -8, 0, 4, -20, 1, 10, 12, 15, -5, 16, 13, 9, 2, 16, 18, 
  15, -7, -16, 4, -7, -5, -10, 16, 14, -3, 22, 20, 9, -37, -22, -16, -11, 5, -14, -5, -16, 6, -12, 0, 14, 15, 16, -40, 24, 10, -2, 4, 13, 0, 20, 17, 25, -3, 15, -12, -28, 10, -8, -8, 9, -19, 11, 27, 30, 28, 6, 39, -7, -24, 9, -25, -29, -16, -12, 6, 36, 11, 29, 20, 7, -37, 30, -4, 0, 3, -4, -33, -30, -8, 12, 15, 8, 16, 29, 69, -3, 8, -2, 1, -2, -9, 0, -2, 10, -1, 3, -63, 17, 8, 11, 0, -19, -12, 5, -7, -7, -8, 7, -15, -1, 9, 1, -4, -6, -1, -16, -1, -5, 8, -4, 9, -16, -47, 17, 1, -8, 1, -5, 1, -18, -5, -4, -14, 0, 2, -36, -4, -3, -10, -2, -13, -18, -3, -4, 5, 5, 4, -2, 
  32, -4, -13, -14, -15, -12, 9, -4, -1, 14, 3, 9, -5, -21, -22, 0, 1, 5, -11, -11, -4, 17, -2, 5, 1, 5, 13, -33, -18, -21, -9, -15, 9, -9, 6, -2, 0, -8, 9, -1, 6, 1, -21, -19, -3, -20, 1, 6, 0, 6, 10, 17, -8, 24, 0, 7, -2, 11, 3, -1, -6, -9, 13, 14, 4, 13, -16, 20, -16, -10, -13, -9, -7, 9, 10, 23, 3, 15, -21, -1, 27, -9, -8, -16, -2, -15, -2, -17, 4, -12, -15, 66, -18, 4, 4, 0, 12, -2, -8, -9, -2, -14, 4, -8, 27, 2, -7, -10, -20, 0, -14, -4, -13, -5, 1, -7, -10, -31, -8, 0, 6, -9, -8, 0, -12, 2, 16, -10, -5, 7, -127, 4, 1, -8, 19, 0, 9, 10, -6, 18, 12, 9, 16, 
  -24, 37, -35, 8, 16, -13, 1, 12, -7, 3, -16, -7, -16, -20, 13, -2, -28, -19, -5, -4, -4, -2, 5, -5, 14, 2, -29, 37, -27, 11, -10, 0, 9, -10, 2, -9, 11, -5, 14, 20, -13, -25, -12, 2, -6, -17, 2, 6, 9, 8, 10, -3, -5, -24, 34, -15, -37, -1, 10, -1, 0, -21, 12, -8, 5, -8, -16, 2, 12, 18, 4, -10, 10, -8, -12, -19, -8, -2, -1, 15, -4, 14, 19, 23, 2, -7, 24, 20, 16, 2, 25, 62, -37, 1, 7, 19, 3, 4, -3, 1, -8, -4, 3, -18, 38, -8, 15, -12, 3, 2, -10, -9, -4, -1, 1, -6, 1, -16, -12, -6, -3, -2, -10, 3, 1, 16, -2, -5, -6, -15, -60, -2, -17, 3, 13, 13, 4, -15, 9, 10, 6, -2, 0, 
  -11, -26, 19, 3, 11, -7, 5, 10, -6, 0, -3, -3, 5, -14, 20, 4, 1, 7, 13, 8, -4, -3, -11, -1, -12, -1, -18, -17, 36, 1, 0, -11, 1, -7, -27, 1, -19, 2, -16, 18, 21, -15, -1, 0, -7, -13, 21, -12, -7, -5, -16, -9, -13, -13, -3, 2, 15, 14, 12, -5, -22, -5, 2, -11, 15, -3, 1, 5, -3, 13, 5, 18, 12, 0, 12, 14, 12, 17, 5, -23, -4, 8, 3, 8, -6, 0, 5, 10, -1, 4, -4, -56, 14, 22, -17, 24, -17, -15, -14, -7, -10, -12, -2, -7, 77, -3, -2, 16, 16, 12, 9, 18, 17, -8, 9, 3, 16, -32, -17, -7, -18, -7, -18, -6, -10, -15, -6, 2, -9, -19, -9, -31, -10, 19, 25, 10, -14, 6, 9, 13, 6, 10, -4, 
  17, -35, 23, -1, -16, -5, -2, 3, -4, 13, -9, 7, -11, 36, -17, -15, 1, -4, 5, 21, 8, -13, -10, -3, -7, 7, 9, 40, 6, -12, -5, 6, -6, -22, -7, -21, -12, -6, 4, 4, 0, 23, 10, 3, 0, -12, -22, -29, -25, -6, -32, -41, 3, 10, -7, -5, -9, -1, 4, -28, -20, 8, -2, -10, -23, 6, 18, 22, -14, 5, -16, -2, -4, 8, -9, -19, -21, -11, -9, 1, 17, -18, 1, -7, 0, -19, 6, 5, 6, -12, -9, -85, 12, -6, -25, -25, -15, -16, -2, 12, -9, 11, 0, -12, -19, 7, 0, -30, -8, -11, -12, -16, 1, 5, 12, -7, 10, -4, 1, 14, -16, 4, -4, -14, 4, 1, -12, -14, -4, -3, -19, 9, 6, -14, 1, 5, -3, -5, -1, -3, -4, 7, 5, 
  7, 15, 12, -4, -15, 12, 0, -7, 1, 0, 3, 11, 11, -8, 0, -4, 4, -9, 16, 5, 16, 12, 15, 8, 11, 12, 9, -3, 14, -15, 6, -10, 0, 2, -10, -2, -11, 15, -8, 0, -7, -6, -15, -7, -15, 2, -7, -4, -10, 3, -16, -17, 13, -12, 5, 5, 0, 5, -4, -8, 8, -5, 11, -8, -1, -17, 16, 14, 7, -10, -8, -6, 1, -14, -7, -15, -13, -9, -11, 10, -6, -11, -10, -8, 12, 3, -1, 5, 8, 8, -1, -15, -14, -2, 10, 0, 16, 6, 9, -6, -8, -7, -5, 9, -1, 8, -7, -1, 0, -2, -7, 10, 3, 7, 12, 14, 5, -12, 13, -5, 7, 10, -1, -5, 8, -14, 3, 15, -13, 12, -16, 15, -13, -7, -14, -1, -10, 14, 5, 14, 14, 0, 11, 
  2, 17, 11, -2, 0, 13, -8, 7, -7, -16, -11, -4, -12, -10, -2, 22, -7, -3, 7, -8, -2, 10, 5, 16, 12, 12, 7, -15, 9, 6, -17, -2, -6, 4, 15, 7, 18, 15, 3, 11, 7, 14, -3, 14, 1, -5, 17, 0, 15, -2, 15, 15, -12, -16, -6, -1, 1, -6, -18, 10, -11, -13, -7, 5, 1, 7, -18, -22, -6, 16, -10, 14, 9, -9, -12, -14, 9, -7, -22, -6, 12, 3, 1, -21, -14, 3, -17, -23, 2, -13, 7, 82, -44, -34, 6, -13, -11, -24, -25, -19, -6, -26, -26, -15, -38, -6, -26, -8, -2, 2, 3, -12, -10, -10, 10, 7, 9, 24, 13, 8, 11, 4, -2, 16, -5, 9, 14, 0, -4, 11, 41, -3, 0, -17, -8, 8, 13, 1, 1, -17, 8, -13, 2, 
  14, -24, 1, -5, -7, -11, -2, -3, -8, 0, -17, 2, -3, -12, 24, 15, 8, -13, 9, 5, -25, 1, -22, 11, 6, -14, 11, 5, 11, 24, 2, -20, -18, -7, 20, 9, -11, -19, -21, 1, -23, 8, 21, 22, 11, 21, -2, -12, 15, 20, 5, 15, -6, 13, 7, 27, -3, 2, 13, 7, 21, 22, 25, 13, 1, -6, 6, 0, 15, 4, 32, 20, -6, 13, 11, 41, 28, 12, 28, 50, -6, -1, 0, 7, 10, 20, -4, 10, 6, -6, -4, 75, 3, -1, 11, -8, 20, 30, 2, 25, 25, 22, 21, 20, -57, -2, 1, -13, 4, 0, -4, -1, 6, 7, -12, 2, -5, 31, 12, -2, -9, 4, -14, -16, 7, -1, -16, -3, 1, -15, 102, -22, -16, -24, -20, 16, 10, -1, 20, 20, 1, -4, 2, 
  3, 22, -17, 11, 14, -19, 6, -8, 6, -4, 9, 11, 4, 9, -25, 3, -6, -4, 11, -2, -7, -6, 12, -2, 2, 7, 37, 56, 13, 12, 23, -4, -6, -5, 4, -4, -11, 2, 5, 15, 21, -1, 3, -23, -12, -8, 4, 12, -17, 8, -7, 11, 13, -10, -17, 17, 28, -5, -4, -13, 5, 6, -4, 2, 8, 12, 8, 15, -6, -4, -19, -1, -3, -12, 9, -11, -1, -1, 9, 47, -2, 23, -21, -8, -14, -12, -13, 8, -6, 9, -1, -85, -7, -1, -19, -26, -19, -2, -12, -12, -7, -4, 4, 6, -35, 10, 3, 24, -13, -9, 1, 6, 10, 8, -9, -6, -10, -7, 19, 14, 33, 2, 7, 3, 5, 0, -3, -5, 22, 19, -77, 13, 2, -1, -7, 6, -8, 15, -4, 11, 3, 4, -1, 
  14, 10, -20, 1, 18, -16, -4, -14, -15, 5, -3, -10, 2, -17, 40, 26, 3, -15, 5, -6, 8, 8, -9, 9, 8, -2, -16, 17, -14, 5, 2, 1, -14, 11, 8, 14, 15, -5, -8, -5, 12, 11, -4, 8, -16, -3, 29, 15, 11, 19, 2, -18, -26, -5, -13, -27, -25, 1, 3, 20, 2, -16, 11, 10, 23, 12, 16, 9, 7, 20, -5, -1, 15, 11, 8, -9, 1, 16, -9, -12, 13, 2, 22, 20, 18, 16, -19, -7, 2, 17, -10, 34, -5, 3, 21, 18, 3, -4, 8, -8, -11, 5, 1, 2, 32, -10, 8, 19, 17, -3, -8, -12, -8, -15, -19, -7, -16, 46, 9, 4, 35, 13, 11, -5, 8, 10, -12, 10, -7, 15, 108, 9, 20, 7, -2, 32, 23, 14, 23, 27, 21, 15, 26, 
  -11, -10, 25, -1, 4, 16, -5, 18, 1, 4, 1, 2, 12, 49, -10, -49, 0, 22, 17, 4, -5, -16, 5, -3, 1, -15, -4, -8, -8, 1, 8, -19, -13, -18, -5, 1, 1, -6, 3, 2, 18, -12, 13, -16, 16, -3, -7, -4, 9, 2, -5, -10, -14, -4, 12, -11, -20, 3, 13, -7, 5, -2, -8, -15, -6, 12, 8, 12, 6, 21, -4, 8, 26, 7, 24, 3, 16, 12, 10, -21, -4, -25, -24, -6, 15, 8, 15, 22, 9, -7, 15, -56, -27, 0, 1, -2, -13, 9, -7, -13, -6, 8, 1, -11, -14, 16, -1, 0, -12, 6, 10, -13, -8, 6, -9, 9, 9, -23, 28, -11, -16, -6, -12, -11, 8, -3, -17, 6, 0, 6, 42, -4, 3, -2, -24, -14, 6, -5, -8, 12, 11, -4, 4, 
  -20, 11, -36, 13, 10, -9, -7, -5, -4, -4, 2, -27, -18, 59, 28, -19, -5, 14, 26, -8, 17, 12, -5, 7, -11, -15, -18, -46, 29, -9, -2, -10, -14, -2, -13, -22, -23, -5, 2, -5, -17, 15, -13, 12, -6, 5, -24, -32, -40, -25, -18, -23, -9, 22, 28, -11, -5, -3, 15, -20, -16, -1, -28, 3, -13, 17, 7, 14, -16, -16, -4, 2, 17, -8, 5, -10, -18, -10, -7, 11, 5, -18, -13, -7, 9, -7, 18, 8, -4, 8, 5, 36, -29, 6, -16, 8, 26, 25, 22, 26, -6, 29, 3, 26, 16, 1, 14, -11, 6, -9, -8, -2, 14, 6, -14, 9, 14, -24, 8, 7, -22, 7, -2, -9, -11, -12, -2, 14, 13, -11, -35, -4, -1, 33, 7, 7, 15, 7, -11, 13, -6, 7, -7, 
  21, 35, 13, -17, -22, 1, -8, -7, 1, 7, 1, 4, -8, 7, 37, 0, 0, -1, -8, -3, -30, 8, -22, -3, -4, -8, 13, -33, 30, -5, -6, -6, -7, 2, 2, 4, -2, -16, 1, 10, 1, 13, 19, 12, 18, -7, -17, 16, 4, 12, 13, 18, 17, 38, 25, -9, 2, 22, -7, 19, 17, 11, 19, 3, 18, 6, 18, 26, 4, -4, -6, 10, -6, 23, 7, 23, -3, 12, 36, 21, -19, 7, -4, 29, 18, 18, 13, 14, 16, 24, -4, 18, 17, -1, 3, 10, -8, 7, 13, 7, 14, 14, 14, -5, 33, -9, -7, 31, 23, 1, 12, -5, -10, 10, 15, -3, 1, -10, -4, 1, 9, -8, -7, -9, 2, -6, -12, -12, -8, -16, 34, -11, 4, 13, -12, -4, -5, -1, 6, 8, -5, 8, -1, 
  -6, -28, -3, 3, 18, 2, -1, -14, 7, -14, -13, -6, 6, -19, -33, 17, -16, -21, -4, -11, -13, -12, 1, -9, 2, -2, -10, -19, -12, 16, 8, 2, 12, -8, -10, -14, 3, -18, -6, -6, -2, -43, 3, 8, -1, -12, 32, -11, -2, -19, -3, -36, -11, -20, -18, -16, 9, -8, 6, -9, -4, 8, -17, -22, -4, 2, 24, -47, 1, 13, -4, -9, -13, -7, 15, 23, -14, 19, -12, 26, 4, -12, -27, -3, 2, 14, 6, -3, 20, 2, 7, -28, 11, -8, -11, -26, -10, -16, 3, -18, -9, -13, -13, -11, 5, 8, 5, 14, -8, -11, 7, 2, 10, -16, -16, 3, -5, -3, -27, -14, -8, -6, -11, -3, 13, 2, -3, -14, 13, 13, -75, -5, -3, 27, -44, 12, 22, 2, 26, 0, 29, 15, 32, 
  -7, 3, 0, 8, 8, -9, -11, 10, 5, 1, -11, 6, -9, 30, -3, 20, -17, -2, 29, -1, 15, 1, 0, 16, -1, -13, -13, 32, -28, -8, 0, -5, -3, -7, -1, 13, 8, -7, 11, -12, -18, 4, 16, 1, 4, -14, -6, 22, -24, -4, -21, -36, 11, 21, 16, -16, -4, -2, 9, -5, 4, 15, 15, 40, 12, 4, -4, 17, 0, -5, 3, -3, 13, 25, 10, -10, -25, -24, 5, -23, -33, 4, 4, 1, 4, 10, -8, 1, -3, 3, -1, 21, -24, 14, 6, 36, 16, 2, 23, -5, 17, 14, 7, -3, 63, 10, -2, 3, -2, -30, -30, -23, -4, -15, -26, -11, -6, 34, -10, -3, -18, 23, 5, 13, -1, 6, 6, 11, 12, 9, -72, 33, 3, 37, 9, -10, 9, 3, -2, -7, -18, -16, -17, 
  -13, 60, -2, -10, -5, -1, -18, -7, -13, -18, -24, -14, -21, -4, -18, 3, 7, -6, -22, -2, -15, 4, -14, 4, -15, -17, 14, 35, -11, -5, 7, -13, -6, -11, 3, 1, -3, -19, -20, 10, 26, -2, -7, -4, 11, 17, 26, 1, -18, -12, 17, 2, 5, -36, 26, -7, -14, -9, -2, 23, -3, -24, -21, -13, -4, -3, 1, -14, 3, 4, 17, 26, 16, -30, -29, -17, -10, -19, -1, 44, -6, -26, -15, 2, 23, 27, 25, 8, 21, 7, 15, 4, 28, 1, 12, -15, -5, -3, 4, -18, -21, 8, -4, -3, -106, -27, -17, 3, -23, 5, -13, -2, -18, -11, -10, -13, 3, 9, -7, -10, 35, -11, 0, 5, 8, 22, -1, -2, 4, 2, 9, -17, 4, 10, -1, -10, 0, 11, -12, -2, 4, -11, -8, 
  4, 41, -11, -17, -19, 5, 16, 10, 18, 18, -6, 20, 16, 9, -43, -46, -1, -6, 0, 15, 0, -5, 19, -4, 8, 9, -7, 3, -4, 15, 9, 9, 24, 1, 9, 15, -4, 11, 9, -4, 8, -16, -7, -11, 6, -5, -13, 13, 9, 15, 16, 31, -13, -3, -7, -22, -22, -8, -6, 15, -10, 15, 9, 25, 8, 4, -17, -1, -14, -9, -12, 15, 0, 7, 10, 15, 0, -8, -29, 9, 17, -26, 3, -12, 4, 10, 9, 0, 8, 6, -3, -27, 8, -5, -27, -32, -18, -17, 9, -16, -11, 3, 3, -19, -11, -3, -11, -27, 5, 12, 18, 15, -9, -6, 10, 6, 0, -27, -21, -9, -8, 9, 5, -9, 3, 9, -14, 0, -7, 6, 8, -3, 14, -10, 15, 3, -5, 0, -22, -19, -7, -24, -9, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,143 } };
const TfArray<1, float> quant6_scale = { 1, { 0.012656840495765209, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.24737977981567383, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.20707309246063232, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,6 } };
const TfArray<1, float> quant9_scale = { 1, { 0.34650534391403198, } };
const TfArray<1, int> quant9_zero = { 1, { 13 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 143, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2860, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 144), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_958037_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_958037_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
